export const TYPES = {
  UserRepository: Symbol.for('UserRepository'),
  GardenRepository: Symbol.for('GardenRepository'),
  DeviceRepository: Symbol.for('DeviceRepository'),
  UserGardenRepository: Symbol.for('UserGardenRepository'),
  UsersService: Symbol.for('UsersService'),
  GardenService: Symbol.for('GardenService'),
  TelemetryServices: Symbol.for('TelemetryServices'),
  UserGardenService: Symbol.for('UserGardenService'),
  TelemetryController: Symbol.for('TelemetryController'),
  UsersController: Symbol.for('UsersController'),
  GardenController: Symbol.for('GardenController'),
  UserGardenController: Symbol.for('UserGardenController'),
  GardenRouter: Symbol.for('GardenRouter'),
  DeviceRouter: Symbol.for('DeviceRouter'),
  UserRouter: Symbol.for('UserRouter'),
  AuthRouter: Symbol.for('AuthRouter'),
  UserGardenRouter: Symbol.for('UserGardenRouter'),
  RequireGardenOwner: Symbol.for('RequireGardenOwner'),
};
